version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install aws-sam-cli
  build:
    commands:
      - echo "== SAM build from ./src =="
      - pwd && ls -la && ls -la src
      - cd src
      # remove --use-container unless CodeBuild project has PrivilegedMode=true
      - sam build
      - echo "== SAM package to repo root packaged.yaml =="
      - sam package --s3-bucket build-packaging-eu-west-1 --output-template-file "$CODEBUILD_SRC_DIR/packaged.yaml"
      - test -s "$CODEBUILD_SRC_DIR/packaged.yaml" && echo "packaged.yaml created:"
      - ls -l "$CODEBUILD_SRC_DIR/packaged.yaml"
artifacts:
  files:
    - packaged.yaml