AWSTemplateFormatVersion: "2010-09-09"
Description: Energy Auction Deployment Pipeline (GitHub → CodePipeline → Lambda + Infra)

Parameters:
  GitHubOwner:
    Type: String
    Default: your-github-username
  GitHubRepo:
    Type: String
    Default: your-github-repo
  GitHubBranch:
    Type: String
    Default: master
  GitHubTokenSecret:
    Type: String
    Default: github-token # stored in Secrets Manager

Resources:
  ###################################################
  # IAM Role for CodePipeline
  ###################################################
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  ###################################################
  # IAM Role for CodeBuild
  ###################################################
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess

  ###################################################
  # CodeBuild Project
  ###################################################
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: EnergyAuctionBuild
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 30
      Cache:
        Type: NO_CACHE
      BuildSpec: |
        version: 0.2
        phases:
          install:
            runtime-versions:
              nodejs: 16
              python: 3.9
            commands:
              - npm install -g aws-cdk
              - npm install
              - pip install -r requirements.txt || true
          build:
            commands:
              - npm run build || true   # for CDK app if needed
              - cdk synth
        artifacts:
          base-directory: cdk.out
          files:
            - "*.template.json"

  ###################################################
  # CodePipeline
  ###################################################
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: EnergyAuctionPipeline
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Sub "${AWS::StackName}-artifacts"
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub_Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Sub "{{resolve:secretsmanager:${GitHubTokenSecret}:SecretString:token}}"
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
        - Name: Deploy
          Actions:
            - Name: CFN_Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: EnergyAuctionApp
                Capabilities: CAPABILITY_IAM
                TemplatePath: BuildOutput::YourAppStack.template.json

  ###################################################
  # S3 Bucket for pipeline artifacts
  ###################################################
  PipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-artifacts"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 7

Outputs:
  PipelineName:
    Value: !Ref Pipeline
    Description: "Name of the CodePipeline"
